tasks:
  - name: Init
    init: yarn              # Install Packages
    command: yarn dev       # Start development server

ports:
  - name: vite dev port
    port: 5173
    onOpen: open-browser
    visibility: public
  
  - name: vite preview port
    port: 4173
    onOpen: open-browser
    visibility: public
